### PR TITLE
new country pages

### PR DESCRIPTION
**Pull request by ClaraIV**
-created a new country page [draft] and added layers from ED.info to replace the current external study
-deleted the Congo country page (no entries)

### CODE REVIEW

**Review by shakythesherpa — APPROVED** [review]
@olafveerman  and @akorkovelos  can one of you review this for pull request from @ClaraIV  and merge.
I am not sure i have the permission to merge the request?

**Review by shakythesherpa — APPROVED** [review]
@olafveerman and @akorkovelos can one of please help merge this pull request from @ClaraIV ?

I am not sure i have the permission to merge any pull requests?

**Comment by olafveerman** [comment]
@shakythesherpa The checks (lint, test, validateConfig) were not running on Pull Requests issued from a fork. I fixed this and updated this branch. All tests pass, and you should be able to merge the PR yourself. Can you check if that's the case?

**Comment by shakythesherpa** [comment]
@olafveerman  I am able to merge the pull request now.  Do you know how long it takes to see the change on the staging website?

**Comment by shakythesherpa** [comment]
@olafveerman  confirming the merge request was successful and i am now able to see all the updates on the staging website. Thanks!

**Pull request merged**
